project:
  type: website
  output-dir: docs

website:
  title: "gizn.org"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - posts.qmd
    right: 
      tools:
      - icon: github
        href: https://github.com/gizngizn

format:
  html:
    theme: [cosmo, theme.scss]
#    css: styles.css
    toc: true

editor: visual

