project:
  type: website
  output-dir: docs

website:
  title: "gizn.org"
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/gizngizn
      - icon: twitter
        menu:
          - text: Bluesky
            href: https://bsky.app/profile/gizn.bsky.social
          - text: X
            href: https://x.com/giznse

    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - posts.qmd

format:
  html:
    theme: [cosmo, theme.scss]
#    css: styles.css
    toc: true

editor: visual

